# Generated by Django 5.2.9 on 2025-12-20 11:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emial', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='emial is not correct', regex='^[a-zA-Z0-9]+@[a-zA-Z]+\\.(com|eur|net)$')])),
                ('password', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='كلمة السر يجب أن تكون 8 أحرف على الأقل وتحتوي على حرف ورقم', regex='^(?=*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='CreatedTime'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/%y/%m/%d'),
        ),
    ]
